language: ruby
script: "bundle exec rspec"
bundler_args: "--without extras"
before_install:
  - gem update --system
  - gem update bundler
  - gem cleanup bundler
rvm:
  - 2.3.0
  - 2.2
  - 2.1
  - jruby-19mode
